import { createFileRoute } from "@tanstack/react-router";
import { LegalLayout, legal, legalHead, legalJsonLd } from "@/components/LegalLayout";

const META = {
  title: "Términos y Condiciones de Uso y Contratación de Rutia",
  description: "Términos y Condiciones de Uso y Contratación del servicio Rutia.",
  path: "/terminos",
};

export const Route = createFileRoute("/terminos")({ component: TermsPage, head: () => legalHead(META) });

function TermsPage() {
  return (
    <LegalLayout title="Términos y Condiciones de Uso y Contratación de Rutia" updated="septiembre 2026" metaLine="Última actualización: septiembre 2026" jsonLd={legalJsonLd(META)} intro={<> </>}>
      <section><h2 className={legal.h2}>Cláusula 1.- Identificación del prestador</h2><p className={legal.p}>Agustín Ariel Devich, con domicilio en Antezana 547, Piso 1, Dpto. B, Ciudad Autónoma de Buenos Aires (en adelante, &quot;el Prestador&quot;), presta el servicio de software de gestión logística bajo la marca Rutia, accesible a través del sitio rutia.com.ar y la aplicación app.rutia.com.ar.</p><p className={legal.p}>Contacto: <a href="mailto:legales@rutia.com.ar" className={legal.link}>legales@rutia.com.ar</a></p><p className={legal.p}>El contenido del sitio y de la aplicación (diseño, marca, código fuente, base de datos, y demás elementos) son propiedad del Prestador o se utilizan bajo licencia según el caso, y están protegidos por la normativa de propiedad intelectual vigente. Su uso no autorizado queda expresamente prohibido.</p></section>
      <section><h2 className={legal.h2}>Cláusula 2.- Objeto</h2><p className={legal.p}>Rutia es un software de gestión logística bajo modalidad SaaS (Software as a Service), destinado a empresas que realizan entregas propias o coordinan fletes contratados, para organizar y controlar la operación desde la preparación del pedido hasta su entrega.</p><p className={legal.p}>Resulta importante destacar que Rutia proporciona la herramienta tecnológica para la gestión de esa operación. No realiza físicamente las entregas ni presta servicios de transporte. Cada empresa usuaria continúa siendo responsable de sus pedidos, clientes, vehículos, choferes/fletes y de la ejecución efectiva de sus entregas.</p></section>
      <section><h2 className={legal.h2}>Cláusula 3.- Aceptación de estos Términos</h2><p className={legal.p}>El acceso y uso de Rutia implica la aceptación plena de estos Términos y Condiciones. La aceptación se perfecciona al momento de crear una cuenta, por medio de la aceptación (marcar la casilla correspondiente), de los Términos y Condiciones. A través de este acto positivo del usuario queda registrada la fecha, hora y versión del documento aceptado.</p><p className={legal.p}>Quien acepta estos Términos en representación de una empresa declara contar con las facultades suficientes para obligarla contractualmente.</p></section>
      <section><h2 className={legal.h2}>Cláusula 4.- Capacidad</h2><p className={legal.p}>El servicio está destinado a personas humanas mayores de edad que actúen en representación de una persona jurídica o humana con capacidad legal para contratar, o a personas jurídicas debidamente constituidas.</p></section>
      <section><h2 className={legal.h2}>Cláusula 5.- Registro y cuenta</h2><p className={legal.p}>Para utilizar Rutia, la empresa debe registrarse y designar un usuario con perfil de administrador/dueño, responsable de gestionar los perfiles adicionales (operaciones, ventas, choferes) dentro de su cuenta.</p><p className={legal.p}>El usuario se compromete a proporcionar información veraz al registrarse, y es responsable de mantener la confidencialidad de sus credenciales de acceso. El Prestador podrá suspender o dar de baja cuentas ante uso indebido, falta de pago, o incumplimiento de estos Términos.</p></section>
      <section><h2 className={legal.h2}>Cláusula 6.- Licencia de uso</h2><p className={legal.p}>El Prestador otorga al usuario una licencia de uso limitada, no exclusiva, intransferible y revocable sobre el software Rutia, exclusivamente para los fines previstos en el objeto de este contrato.</p><p className={legal.p}>El usuario no adquiere derecho de propiedad alguno sobre el software, su código fuente, diseño o marca.</p></section>
      <section><h2 className={legal.h2}>Cláusula 7.- Período de prueba y planes</h2><h3 className={legal.h3}>7.1. Período de prueba</h3><p className={legal.p}>Rutia ofrece un período de prueba gratuito, sin necesidad de método de pago previo, cuya duración se informa al momento del registro.</p><p className={legal.p}>Vencido dicho plazo sin que el usuario contrate un plan, la cuenta pasa a modalidad de solo lectura, conservando el acceso a la información cargada, sin posibilidad de operar nuevas funcionalidades hasta tanto se contrate un plan.</p><h3 className={legal.h3}>7.2. Suscripción paga</h3><p className={legal.p}>Si el usuario decide continuar utilizando Rutia una vez vencido el período de prueba, deberá cargar un método de pago válido, quedando sujeto a una suscripción mensual por tiempo indeterminado con débito automático, conforme al plan seleccionado.</p><p className={legal.p}>Rutia ofrece distintos planes de suscripción, diferenciados exclusivamente por la cantidad de entregas mensuales incluidas, sin distinción de funcionalidades entre ellos: Plan Inicial (hasta 150 entregas mensuales), Plan PyME (hasta 600 entregas mensuales), Plan Empresa (hasta 2.000 entregas mensuales).</p><p className={legal.p}>Los volúmenes superiores a 2.000 entregas mensuales se evalúan de forma personalizada. Se computa como entrega aquella que ingresa efectivamente a la planificación operativa, no la mera carga o importación de un pedido; una reprogramación que genere una nueva asignación operativa podrá computarse nuevamente.</p><h3 className={legal.h3}>7.3. Régimen de renovación automática y baja</h3><p className={legal.p}>Conforme a la Resolución N° 424/2020 de la Secretaría de Comercio Interior, el Prestador informa expresamente que la suscripción se renueva automáticamente mes a mes mediante débito automático, salvo cancelación previa por parte del usuario. La cancelación puede realizarse en todo momento, mediante un procedimiento tan sencillo y accesible como el utilizado para contratar el servicio, sin costo adicional.</p></section>
      <section><h2 className={legal.h2}>Cláusula 8.- Medios de pago</h2><p className={legal.p}>Los medios de pago habilitados se informan en la plataforma al momento de la contratación y pueden actualizarse sin necesidad de modificar el presente documento.</p></section>
      <section><h2 className={legal.h2}>Cláusula 9.- Obligaciones del usuario y usos prohibidos</h2><p className={legal.p}>El usuario se compromete a utilizar Rutia conforme a su finalidad, y en particular se obliga a no:</p><ul className={legal.ul}><li>Realizar ingeniería inversa, descompilar o intentar extraer el código fuente del software.</li><li>Utilizar el servicio para fines ilícitos o contrarios a la buena fe.</li><li>Sobrecargar deliberadamente la infraestructura del sistema.</li><li>Ceder, sublicenciar o compartir sus credenciales de acceso con terceros no autorizados.</li><li>Incorporar en los campos de observaciones o notas del sistema datos personales sensibles (en los términos del artículo 2° de la Ley 25.326) que no resulten necesarios para la prestación del servicio logístico.</li></ul></section>
      <section><h2 className={legal.h2}>Cláusula 10.- Disponibilidad del servicio</h2><p className={legal.p}>El Prestador realiza sus mejores esfuerzos para mantener el servicio disponible de forma continua, sin garantizar disponibilidad ininterrumpida. Podrán existir interrupciones programadas por mantenimiento, que se procurará informar con antelación razonable, así como interrupciones no programadas por causas ajenas al Prestador.</p></section>
      <section><h2 className={legal.h2}>Cláusula 11.- Garantías</h2><p className={legal.p}>El servicio se presta sin garantías de ningún tipo respecto de su idoneidad para un fin específico, salvo las que resulten de aplicación obligatoria conforme a la normativa vigente.</p></section>
      <section><h2 className={legal.h2}>Cláusula 12.- Limitación de responsabilidad</h2><p className={legal.p}>El Prestador no será responsable por daños indirectos, lucro cesante, o pérdida de datos derivados del uso del servicio, salvo en los casos de dolo o culpa grave, conforme lo dispuesto por el artículo 1743 del Código Civil y Comercial de la Nación.</p><p className={legal.p}>El Prestador no es responsable por la ejecución material de las entregas, la que corresponde exclusivamente a la empresa usuaria y a los choferes o fletes que ésta designe, lo que resulta ajeno al objeto de Rutia especificado en la cláusula número 2 (dos).</p></section>
      <section><h2 className={legal.h2}>Cláusula 13.- Indemnidad</h2><p className={legal.p}>El usuario mantendrá indemne al Prestador frente a cualquier reclamo de terceros derivado del uso indebido del servicio o del incumplimiento de estos Términos por parte del usuario.</p></section>
      <section><h2 className={legal.h2}>Cláusula 14.- Botón de arrepentimiento</h2><p className={legal.p}>Conforme a la Resolución N° 424/2020, el usuario que contrate el servicio a través del sitio web cuenta con un plazo de 10 (diez) días corridos desde la contratación para ejercer su derecho de revocación, sin costo y sin necesidad de invocar motivo alguno, conforme el artículo 34 de la Ley N° 24.240 y el artículo 1110 del Código Civil y Comercial de la Nación.</p></section>
      <section><h2 className={legal.h2}>Cláusula 15.- Cesión de posición contractual</h2><p className={legal.p}>El Prestador podrá ceder su posición contractual en estos Términos y Condiciones a una sociedad que continúe la explotación del servicio Rutia, notificando dicha cesión al usuario por los medios de contacto registrados. La cesión no requerirá aceptación expresa del usuario, sin perjuicio de su derecho a dar de baja el servicio conforme lo previsto en el punto 7.3.</p></section>
      <section><h2 className={legal.h2}>Cláusula 16.- Modificaciones</h2><p className={legal.p}>El Prestador podrá modificar estos Términos y Condiciones. Los cambios serán notificados a los usuarios con una antelación no menor a 15 (quince) días corridos respecto de su entrada en vigencia, indicando la fecha a partir de la cual rige la nueva versión. El uso continuado del servicio con posterioridad a dicha fecha implica la aceptación de los términos modificados. El usuario que no esté de acuerdo con los cambios podrá dar de baja el servicio antes de que estos entren en vigencia, conforme lo previsto en la cláusula 7.3.</p></section>
      <section><h2 className={legal.h2}>Cláusula 17.- Terminación</h2><p className={legal.p}>Cualquiera de las partes podrá dar por terminada la relación conforme lo previsto en la cláusula 7.3. El Prestador podrá además suspender o dar de baja el servicio ante incumplimientos graves del usuario, previa notificación cuando las circunstancias lo permitan.</p></section>
      <section><h2 className={legal.h2}>Cláusula 18.- Datos personales</h2><p className={legal.p}>El tratamiento de datos personales por parte del Prestador se rige por la Política de Privacidad y, respecto de los datos que las empresas usuarias cargan de sus propios clientes/destinatarios, por el Acuerdo de Encargado de Tratamiento suscripto entre las partes.</p></section>
      <section><h2 className={legal.h2}>Cláusula 19.- Ley aplicable y jurisdicción</h2><p className={legal.p}>Estos Términos y Condiciones se rigen por las leyes de la República Argentina. Para cualquier controversia derivada del presente, las partes se someten a los tribunales ordinarios competentes de la Ciudad Autónoma de Buenos Aires, sin perjuicio de las normas de protección al consumidor que resulten de aplicación obligatoria según el domicilio del usuario.</p></section>
      <section><h2 className={legal.h2}>Cláusula 20.- Resolución de conflictos</h2><p className={legal.p}>Las partes procurarán resolver amistosamente cualquier controversia antes de recurrir a la vía judicial.</p></section>
    </LegalLayout>
  );
}
