/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as LogisticaParaMuebleriasRouteImport } from './routes/logistica-para-mueblerias'
import { Route as LogisticaParaIluminacionRouteImport } from './routes/logistica-para-iluminacion'
import { Route as LogisticaParaFerreteriasRouteImport } from './routes/logistica-para-ferreterias'
import { Route as LogisticaParaElectrodomesticosRouteImport } from './routes/logistica-para-electrodomesticos'
import { Route as LogisticaParaEcommerceRouteImport } from './routes/logistica-para-ecommerce'
import { Route as LogisticaParaDistribuidorasRouteImport } from './routes/logistica-para-distribuidoras'
import { Route as LogisticaParaCorralonesRouteImport } from './routes/logistica-para-corralones'
import { Route as LogisticaParaColchoneriasRouteImport } from './routes/logistica-para-colchonerias'
import { Route as LogisticaParaCasasDeMaterialesRouteImport } from './routes/logistica-para-casas-de-materiales'
import { Route as LogisticaParaBicicleteriasRouteImport } from './routes/logistica-para-bicicleterias'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiContactRouteImport } from './routes/api.contact'
import { Route as BlogCategoriaCategoriaRouteImport } from './routes/blog/categoria.$categoria'

const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticaParaMuebleriasRoute = LogisticaParaMuebleriasRouteImport.update({
  id: '/logistica-para-mueblerias',
  path: '/logistica-para-mueblerias',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticaParaIluminacionRoute =
  LogisticaParaIluminacionRouteImport.update({
    id: '/logistica-para-iluminacion',
    path: '/logistica-para-iluminacion',
    getParentRoute: () => rootRouteImport,
  } as any)
const LogisticaParaFerreteriasRoute =
  LogisticaParaFerreteriasRouteImport.update({
    id: '/logistica-para-ferreterias',
    path: '/logistica-para-ferreterias',
    getParentRoute: () => rootRouteImport,
  } as any)
const LogisticaParaElectrodomesticosRoute =
  LogisticaParaElectrodomesticosRouteImport.update({
    id: '/logistica-para-electrodomesticos',
    path: '/logistica-para-electrodomesticos',
    getParentRoute: () => rootRouteImport,
  } as any)
const LogisticaParaEcommerceRoute = LogisticaParaEcommerceRouteImport.update({
  id: '/logistica-para-ecommerce',
  path: '/logistica-para-ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticaParaDistribuidorasRoute =
  LogisticaParaDistribuidorasRouteImport.update({
    id: '/logistica-para-distribuidoras',
    path: '/logistica-para-distribuidoras',
    getParentRoute: () => rootRouteImport,
  } as any)
const LogisticaParaCorralonesRoute = LogisticaParaCorralonesRouteImport.update({
  id: '/logistica-para-corralones',
  path: '/logistica-para-corralones',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticaParaColchoneriasRoute =
  LogisticaParaColchoneriasRouteImport.update({
    id: '/logistica-para-colchonerias',
    path: '/logistica-para-colchonerias',
    getParentRoute: () => rootRouteImport,
  } as any)
const LogisticaParaCasasDeMaterialesRoute =
  LogisticaParaCasasDeMaterialesRouteImport.update({
    id: '/logistica-para-casas-de-materiales',
    path: '/logistica-para-casas-de-materiales',
    getParentRoute: () => rootRouteImport,
  } as any)
const LogisticaParaBicicleteriasRoute =
  LogisticaParaBicicleteriasRouteImport.update({
    id: '/logistica-para-bicicleterias',
    path: '/logistica-para-bicicleterias',
    getParentRoute: () => rootRouteImport,
  } as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategoriaCategoriaRoute = BlogCategoriaCategoriaRouteImport.update({
  id: '/blog/categoria/$categoria',
  path: '/blog/categoria/$categoria',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/cookies': typeof CookiesRoute
  '/logistica-para-bicicleterias': typeof LogisticaParaBicicleteriasRoute
  '/logistica-para-casas-de-materiales': typeof LogisticaParaCasasDeMaterialesRoute
  '/logistica-para-colchonerias': typeof LogisticaParaColchoneriasRoute
  '/logistica-para-corralones': typeof LogisticaParaCorralonesRoute
  '/logistica-para-distribuidoras': typeof LogisticaParaDistribuidorasRoute
  '/logistica-para-ecommerce': typeof LogisticaParaEcommerceRoute
  '/logistica-para-electrodomesticos': typeof LogisticaParaElectrodomesticosRoute
  '/logistica-para-ferreterias': typeof LogisticaParaFerreteriasRoute
  '/logistica-para-iluminacion': typeof LogisticaParaIluminacionRoute
  '/logistica-para-mueblerias': typeof LogisticaParaMuebleriasRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/api/contact': typeof ApiContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/categoria/$categoria': typeof BlogCategoriaCategoriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/cookies': typeof CookiesRoute
  '/logistica-para-bicicleterias': typeof LogisticaParaBicicleteriasRoute
  '/logistica-para-casas-de-materiales': typeof LogisticaParaCasasDeMaterialesRoute
  '/logistica-para-colchonerias': typeof LogisticaParaColchoneriasRoute
  '/logistica-para-corralones': typeof LogisticaParaCorralonesRoute
  '/logistica-para-distribuidoras': typeof LogisticaParaDistribuidorasRoute
  '/logistica-para-ecommerce': typeof LogisticaParaEcommerceRoute
  '/logistica-para-electrodomesticos': typeof LogisticaParaElectrodomesticosRoute
  '/logistica-para-ferreterias': typeof LogisticaParaFerreteriasRoute
  '/logistica-para-iluminacion': typeof LogisticaParaIluminacionRoute
  '/logistica-para-mueblerias': typeof LogisticaParaMuebleriasRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/api/contact': typeof ApiContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/blog/categoria/$categoria': typeof BlogCategoriaCategoriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/cookies': typeof CookiesRoute
  '/logistica-para-bicicleterias': typeof LogisticaParaBicicleteriasRoute
  '/logistica-para-casas-de-materiales': typeof LogisticaParaCasasDeMaterialesRoute
  '/logistica-para-colchonerias': typeof LogisticaParaColchoneriasRoute
  '/logistica-para-corralones': typeof LogisticaParaCorralonesRoute
  '/logistica-para-distribuidoras': typeof LogisticaParaDistribuidorasRoute
  '/logistica-para-ecommerce': typeof LogisticaParaEcommerceRoute
  '/logistica-para-electrodomesticos': typeof LogisticaParaElectrodomesticosRoute
  '/logistica-para-ferreterias': typeof LogisticaParaFerreteriasRoute
  '/logistica-para-iluminacion': typeof LogisticaParaIluminacionRoute
  '/logistica-para-mueblerias': typeof LogisticaParaMuebleriasRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/api/contact': typeof ApiContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/blog/categoria/$categoria': typeof BlogCategoriaCategoriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aviso-legal'
    | '/cookies'
    | '/logistica-para-bicicleterias'
    | '/logistica-para-casas-de-materiales'
    | '/logistica-para-colchonerias'
    | '/logistica-para-corralones'
    | '/logistica-para-distribuidoras'
    | '/logistica-para-ecommerce'
    | '/logistica-para-electrodomesticos'
    | '/logistica-para-ferreterias'
    | '/logistica-para-iluminacion'
    | '/logistica-para-mueblerias'
    | '/privacidad'
    | '/terminos'
    | '/api/contact'
    | '/blog/$slug'
    | '/blog/'
    | '/blog/categoria/$categoria'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-legal'
    | '/cookies'
    | '/logistica-para-bicicleterias'
    | '/logistica-para-casas-de-materiales'
    | '/logistica-para-colchonerias'
    | '/logistica-para-corralones'
    | '/logistica-para-distribuidoras'
    | '/logistica-para-ecommerce'
    | '/logistica-para-electrodomesticos'
    | '/logistica-para-ferreterias'
    | '/logistica-para-iluminacion'
    | '/logistica-para-mueblerias'
    | '/privacidad'
    | '/terminos'
    | '/api/contact'
    | '/blog/$slug'
    | '/blog'
    | '/blog/categoria/$categoria'
  id:
    | '__root__'
    | '/'
    | '/aviso-legal'
    | '/cookies'
    | '/logistica-para-bicicleterias'
    | '/logistica-para-casas-de-materiales'
    | '/logistica-para-colchonerias'
    | '/logistica-para-corralones'
    | '/logistica-para-distribuidoras'
    | '/logistica-para-ecommerce'
    | '/logistica-para-electrodomesticos'
    | '/logistica-para-ferreterias'
    | '/logistica-para-iluminacion'
    | '/logistica-para-mueblerias'
    | '/privacidad'
    | '/terminos'
    | '/api/contact'
    | '/blog/$slug'
    | '/blog/'
    | '/blog/categoria/$categoria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  CookiesRoute: typeof CookiesRoute
  LogisticaParaBicicleteriasRoute: typeof LogisticaParaBicicleteriasRoute
  LogisticaParaCasasDeMaterialesRoute: typeof LogisticaParaCasasDeMaterialesRoute
  LogisticaParaColchoneriasRoute: typeof LogisticaParaColchoneriasRoute
  LogisticaParaCorralonesRoute: typeof LogisticaParaCorralonesRoute
  LogisticaParaDistribuidorasRoute: typeof LogisticaParaDistribuidorasRoute
  LogisticaParaEcommerceRoute: typeof LogisticaParaEcommerceRoute
  LogisticaParaElectrodomesticosRoute: typeof LogisticaParaElectrodomesticosRoute
  LogisticaParaFerreteriasRoute: typeof LogisticaParaFerreteriasRoute
  LogisticaParaIluminacionRoute: typeof LogisticaParaIluminacionRoute
  LogisticaParaMuebleriasRoute: typeof LogisticaParaMuebleriasRoute
  PrivacidadRoute: typeof PrivacidadRoute
  TerminosRoute: typeof TerminosRoute
  ApiContactRoute: typeof ApiContactRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogCategoriaCategoriaRoute: typeof BlogCategoriaCategoriaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistica-para-mueblerias': {
      id: '/logistica-para-mueblerias'
      path: '/logistica-para-mueblerias'
      fullPath: '/logistica-para-mueblerias'
      preLoaderRoute: typeof LogisticaParaMuebleriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistica-para-iluminacion': {
      id: '/logistica-para-iluminacion'
      path: '/logistica-para-iluminacion'
      fullPath: '/logistica-para-iluminacion'
      preLoaderRoute: typeof LogisticaParaIluminacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistica-para-ferreterias': {
      id: '/logistica-para-ferreterias'
      path: '/logistica-para-ferreterias'
      fullPath: '/logistica-para-ferreterias'
      preLoaderRoute: typeof LogisticaParaFerreteriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistica-para-electrodomesticos': {
      id: '/logistica-para-electrodomesticos'
      path: '/logistica-para-electrodomesticos'
      fullPath: '/logistica-para-electrodomesticos'
      preLoaderRoute: typeof LogisticaParaElectrodomesticosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistica-para-ecommerce': {
      id: '/logistica-para-ecommerce'
      path: '/logistica-para-ecommerce'
      fullPath: '/logistica-para-ecommerce'
      preLoaderRoute: typeof LogisticaParaEcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistica-para-distribuidoras': {
      id: '/logistica-para-distribuidoras'
      path: '/logistica-para-distribuidoras'
      fullPath: '/logistica-para-distribuidoras'
      preLoaderRoute: typeof LogisticaParaDistribuidorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistica-para-corralones': {
      id: '/logistica-para-corralones'
      path: '/logistica-para-corralones'
      fullPath: '/logistica-para-corralones'
      preLoaderRoute: typeof LogisticaParaCorralonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistica-para-colchonerias': {
      id: '/logistica-para-colchonerias'
      path: '/logistica-para-colchonerias'
      fullPath: '/logistica-para-colchonerias'
      preLoaderRoute: typeof LogisticaParaColchoneriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistica-para-casas-de-materiales': {
      id: '/logistica-para-casas-de-materiales'
      path: '/logistica-para-casas-de-materiales'
      fullPath: '/logistica-para-casas-de-materiales'
      preLoaderRoute: typeof LogisticaParaCasasDeMaterialesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistica-para-bicicleterias': {
      id: '/logistica-para-bicicleterias'
      path: '/logistica-para-bicicleterias'
      fullPath: '/logistica-para-bicicleterias'
      preLoaderRoute: typeof LogisticaParaBicicleteriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/categoria/$categoria': {
      id: '/blog/categoria/$categoria'
      path: '/blog/categoria/$categoria'
      fullPath: '/blog/categoria/$categoria'
      preLoaderRoute: typeof BlogCategoriaCategoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  CookiesRoute: CookiesRoute,
  LogisticaParaBicicleteriasRoute: LogisticaParaBicicleteriasRoute,
  LogisticaParaCasasDeMaterialesRoute: LogisticaParaCasasDeMaterialesRoute,
  LogisticaParaColchoneriasRoute: LogisticaParaColchoneriasRoute,
  LogisticaParaCorralonesRoute: LogisticaParaCorralonesRoute,
  LogisticaParaDistribuidorasRoute: LogisticaParaDistribuidorasRoute,
  LogisticaParaEcommerceRoute: LogisticaParaEcommerceRoute,
  LogisticaParaElectrodomesticosRoute: LogisticaParaElectrodomesticosRoute,
  LogisticaParaFerreteriasRoute: LogisticaParaFerreteriasRoute,
  LogisticaParaIluminacionRoute: LogisticaParaIluminacionRoute,
  LogisticaParaMuebleriasRoute: LogisticaParaMuebleriasRoute,
  PrivacidadRoute: PrivacidadRoute,
  TerminosRoute: TerminosRoute,
  ApiContactRoute: ApiContactRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogCategoriaCategoriaRoute: BlogCategoriaCategoriaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
